# for commit
# first commit
server:
  port: ${PORT:8080}
  forward-headers-strategy: native

spring:
  config:
    import: optional:file:.env.properties
  datasource:
    url: jdbc:mysql:///${DB_NAME}?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB  # 최대 파일 크기
      max-request-size: 10MB  # 최대 요청 크기



  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # Deprecated 경고 제거
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"


          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:5173/callback"
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}

fastapi:
  server:
    url: ${FASTAPI_CLOUD_RUN_URL}

frontend:
  url: https://gyeol-three.vercel.app/


#cloud:
#  aws:
#    s3:
#      bucket: gyeol-image-bucket
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false

gcp:
  storage:
    bucket: ${GCS_BUCKET_NAME}
    project-id: ${PROJECT_ID}